server:
  port: 443
  ssl:
    key-alias: tomcat
    key-password: 123456
    key-store: classpath:.keystore
    key-store-type: JKS
    protocol: TLS
app:
  http2https: true      #开启http-> https

  #spring boot data jpa  配置
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      indent_output: true  #JSON输出更完美



